### ISSUE TITLE
Can't align sponsors nicely

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/cambrainhack2017#1]
Hi @akeshavan - do you have any time to let me know how to better align the sponsors at the bottom of the page? They're currently in one column and left aligned which looks kinda strange - two columns probably make most sense if possible??

Thank you!

**Comment by akeshavan** [comment]
Check out https://github.com/KirstieJane/cambrainhack2017/pull/2 !

**Comment by KirstieJane** [comment]
Woooo! 💯
